default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskmanager4_development
  username: debian
  password: debian

test:
  <<: *default
  database: taskmanager4_test
  username: debian
  password: debian

production:
  <<: *default
  database: taskmanager4_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
